#!/usr/bin/env bash
#Command script to run pingpong performance testing on multiple machines as MPI task on Azure Batch.
#Usage: application-cmd [nodes]

#For more details of MPI/RDMA, visit: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/classic/rdma-cluster

#Use the intel mpi exists in CentOS-HPC 7.4 image
#source /opt/intel/impi/5.1.3.223/bin64/mpivars.sh
#prepare environment variables for intel mpi to use RDMA

# TCP comms could work on any instance type, but you need to disable direct
#export I_MPI_FABRICS=tcp

export I_MPI_FABRICS=shm:dapl
export I_MPI_DAPL_PROVIDER=ofa-v2-ib0

export I_MPI_DYNAMIC_CONNECTION=0

# Run mpi application with appropriate parameters
#mpirun -n $1 -ppn `nproc` -hosts $AZ_BATCH_HOST_LIST IMB-MPI1 pingpong


sudo chmod 777 /mnt
sudo yum -y install epel-release
sudo yum -y install cmake git makedepf90
sudo yum -y install netcdf netcdf-devel netcdf-fortran-devel netcdf-fortran netcdf-static 
sudo yum -y install openmpi openmpi-devel netcdf-fortran-openmpi-devel  

export PATH=$PATH:/usr/lib64/openmpi/bin/
cd WHEREVER
make clean
make libs -j
make gotm -j
make fvcom -j

cp GOTM_source\fvcom place\_run



# source /opt/intel/compilers_and_libraries/linux/bin/compilervars.sh


mpirun -n $1 -ppn `nproc` -hosts $AZ_BATCH_HOST_LIST fvcom --CASENAME=wvi_inlets4
